# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fad4b16255f7800e4cea2a62d609b6b0efe7575f19d69650ca6209c264600f3540976550fa983b94172035aab10978aaafb32d6e8f0afec66318bfc2b317f98

test:
  secret_key_base: 3cd44c1857d0f0e13f8cf8517b65e4ecf9a6f54ed11c293b8382d855f6e7693ad581bb9d2b9aee388d198a68d1b5c566062fd83d980a7e748bd27766337ec52a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
